<?php

declare(strict_types=1);

namespace MichielRoos\WizardCrpagetree\ContextMenu;

use TYPO3\CMS\Backend\ContextMenu\ItemProviders\PageProvider;
use TYPO3\CMS\Backend\Routing\Exception\RouteNotFoundException;
use TYPO3\CMS\Backend\Routing\UriBuilder;
use TYPO3\CMS\Core\Utility\GeneralUtility;

class ItemProvider extends PageProvider
{
    /**
     * @var array<string,array<string,string>>
     */
    protected $itemsConfiguration = [
        'pagesNewTree' => [
            'label'          => 'LLL:EXT:wizard_crpagetree/Resources/Private/Language/locallang.xlf:title',
            'iconIdentifier' => 'apps-pagetree-drag-move-between',
            'callbackAction' => 'pagesNewTree',
        ],
    ];

    /**
     * This method adds custom item to list of items generated by item providers with higher priority value (PageProvider)
     * You could also modify existing items here.
     * The new item is added after the 'info' item.
     *
     * @param array<string,mixed> $items
     * @return array<string,mixed>
     */
    public function addItems(array $items): array
    {
        $this->initialize();
        $this->initDisabledItems();

        // renders an item based on the configuration from $this->itemsConfiguration
        $localItems = $this->prepareItems($this->itemsConfiguration);
        if ($localItems === []) {
            return $items;
        }

        // The 'info' item is not available on the root page, so fall back to the 'new' item
        $anchor = null;
        foreach (['info', 'new'] as $candidate) {
            if (isset($items[$candidate])) {
                $anchor = $candidate;
                break;
            }
        }

        if ($anchor !== null) {
            //finds a position of the item after which this item should be added
            $position = (int)array_search($anchor, array_keys($items), true);

            // slices array into two parts
            $beginning = array_slice($items, 0, $position + 1, true);
            $end = array_slice($items, $position + 1, null, true);

            // adds custom item in the correct position
            $items = $beginning + $localItems + $end;
        } else {
            $items += $localItems;
        }
        //passes array of items to the next item provider
        return $items;
    }

    /**
     * Returns the provider priority which is used for determining the order in which providers are processing items
     * to the result array. Highest priority means provider is evaluated first.
     *
     * This item provider should be called after PageProvider which has priority 100.
     *
     * BEWARE: Returned priority should logically not clash with another provider.
     *         Please check @return int
     * @see \TYPO3\CMS\Backend\ContextMenu\ContextMenu::getAvailableProviders() if needed.
     */
    public function getPriority(): int
    {
        return 90;
    }

    /**
     * @param string $itemName
     * @return array|string[]
     * @throws RouteNotFoundException
     */
    protected function getAdditionalAttributes(string $itemName): array
    {
        $attributes = [];
        if ($itemName === 'pagesNewTree') {
            /** @var Uribuilder $uriBuilder */
            $uriBuilder = GeneralUtility::makeInstance(UriBuilder::class);
            $attributes += [
                'data-page-new-tree-url' => (string)$uriBuilder->buildUriFromRoute('pagetree_new', ['id' => $this->record['uid'] ?? 0]),
                'data-callback-module' => '@michielroos/wizardcrpagetree/context-menu-actions',
            ];
        }
        return $attributes;
    }

    /**
     * This method is called for each item this provider adds and checks if given item can be added
     *
     * @param string $itemName
     * @param string $type
     * @return bool
     */
    protected function canRender(string $itemName, string $type): bool
    {
        // checking if item is disabled through TSConfig
        if (in_array($itemName, $this->disabledItems, true)) {
            return false;
        }
        return $itemName === 'pagesNewTree' && $this->canBeCreated();
    }
}
